poll_website/poll_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

poll_website/polls/urls.py
from django.urls import path, include
from . import views


app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', include([
        path('', views.detail, name='detail'),
        path('results/', views.results, name='results'),
        path('vote/', views.vote, name='vote'),
    ])),
]

poll_website/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    # Тут прописываем поля класса модели, т.е. задаем ей свойства.
    # Каждый тип модели говорит Джанго, какой там тип данных.
    # Имена этих переменных будут использованы БД как имена столбцов, если не указан арг, как в "pub_date" ниже.

    question_text = models.CharField(max_length=200)  # Задаем максимальную длину цифро-буквенного поля
    pub_date = models.DateTimeField('date published')  # Поле для даты и времени, необязательный арг - имя поля
    # objects = models.Manager()
    def __str__(self):
        return self.question_text

    def was_published_recently(self) -> bool:
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # Это поле отношений, т.е. связи между моделями.
                                                                      # ПОКА ХЗ ЧТО ЭТО
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)  # Числовое поле с нулем по дефолту

    def __str__(self):
        return self.choice_text

poll_website/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
# from django.template import loader

from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question} )


def results(request, question_id):
    return HttpResponse(f"You're looking at the results of question {question_id}")


def vote(request, question_id):
    return HttpResponse(f"You're voting on question {question_id}")

poll_website/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail page</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
</body>
</html>

poll_website/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Some title here</title>
</head>
<body>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>